version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout

      - run:
          name: Install packages
          command: sudo apt-get update && sudo apt-get install wget zip unzip -y
      - run:
          name: Install pip
          command: sudo apt-get install python-pip -y
      - run:
          name: Install awscli
          command: sudo pip install awscli

      - run:
          name: Scripts
          command: |
            cd CloudWebApp
            pwd
            ls -al
            mvn clean package -DskipTests=true
            cd target/
            ls -al
            cd ../
            pwd
            ls -al

      - run:
          name: deploy to s3
          command: |
            pwd
            mkdir lambda_artifact
            zip -r csye6225-lambda-${CIRCLE_BUILD_NUM}.zip lambda/target/lambda-1.0-SNAPSHOT.jar
            mv csye6225-lambda-${CIRCLE_BUILD_NUM}.zip lambda_artifact/
            ls -al
            pwd
            ls -al
            aws s3 sync lambda_artifact s3://lambda.csye6225-spring2019-${BUCKETNAME}.me --region us-east-1
            echo "export RoleArn=$(aws iam list-roles --query 'Roles[?RoleName==`LambdaSNSRole`].Arn' --output text)" >> $BASH_ENV

      - run:
          name: create function
          command: |
            aws lambda create-function --function-name password-reset --runtime java8 --environment Variables={DOMAIN=${DOMAIN}} --memory-size 256 --role ${RoleArn} --handler Event:handeleRequest --code S3Bucket=lambda.csye6225-spring2019-${BUCKETNAME}.me,S3Key=csye6225-lambda-${CIRCLE_BUILD_NUM}.zip --region us-east-1
	

